name: internalinformationmanagement
description: "System for IATECH"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  http: ^1.2.1
  mysql1: ^0.20.0
  dot_navigation_bar: ^1.0.2
  email_validator: ^2.1.17
  provider: ^6.1.2
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2
  flutter_dotenv: ^5.1.0
  mask_text_input_formatter: ^2.9.0
  crypto: ^3.0.3
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  shared_preferences: ^2.2.2
  flutter_flavorizr: ^2.2.2
  sliding_clipped_nav_bar: ^3.1.1
  motion_tab_bar: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "G.I. DSA Dev"
      android:
        applicationId: "adventistas.org.internalinformationmanagement"
      ios:
        bundleId: "adventistas.org.internalinformationmanagement"
    hom:
      app:
        name: "G.I. DSA hom"
      android:
        applicationId: "adventistas.org.internalinformationmanagement"
      ios:
        bundleId: "adventistas.org.internalinformationmanagement"
    prod:
      app:
        name: "G.I. DSA Prod"
      android:
        applicationId: "adventistas.org.internalinformationmanagement"
      ios:
        bundleId: "adventistas.org.internalinformationmanagement"

  flutter_lints: ^3.0.1



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/imgs/
    - assets/svgs/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
